---
- name: tp0
  hosts: all
  remote_user: root

  tasks:
  - name: Installer VIM
    apt:
      name: vim
      state: present

  - name: Vérifier la présence du fichier /etc/passwd
    stat:
      path: /etc/passwd
